### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by AlanKK** [gmr/tornado-dynamodb#1]
Hi Gavin,

I found your project and think it looks like what I need.  I am having some trouble getting it working though and want to know what state it is in.  I am using python 2.7 and Tornado 4.3.  Here's my error:

2016-03-13 11:25:21,367 ERROR   : pid=06727 Exception in callback <functools.partial object at 0xb6282c84>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "build/bdist.linux-i686/egg/tornado_aws/client.py", line 479, in on_response
    awz_error = self._awz_error(exception)
  File "build/bdist.linux-i686/egg/tornado_aws/client.py", line 179, in _awz_error
    if error.code == 400:
AttributeError: 'exceptions.TypeError' object has no attribute 'code'

and my code:

       dynamodb = tornado_dynamodb.DynamoDB(
                        region='us-east-1', 
                        access_key = 'accesskey',
                        secret_key = 'skey',
                        max_clients = 1000
                    )

        # TODO: add yield
        response = yield dynamodb.get_item(
                                    'file_record', 
                                    {'shorthash': hash[:3], 'sha256': hash}
                                )

**Comment by AlanKK** [comment]
I get the same error when using tornado-aws directly.

**Comment by gmr** [comment]
Hey, sorry for the delay in response. I should close this down as all development has been moved to https://github.com/sprockets/sprockets.clients.dynamodb.  That being said, this is an error in tornado-aws and I'll look to get an update out shortly.
